### ISSUE TITLE
request for adding chat type or thread type service

### ISSUE THREAD

**Issue by haseeb-catalyst** [shivampaw/UltimateCRM#19]
chat or thread type service where the client and user or admin can exchange photos doc etc

**Comment by shivampaw** [comment]
Interesting idea! Will implement it when I get some time :)

**Comment by shivampaw** [comment]
Hi

I've added it to the latest version which PR #23  which has the release notes and how to upgrade :)

Run 

```
git pull
composer install
npm install
npm run dev
php artisan migrate
```

Let me know if you have any issues.

PR #24 adds email notifications which is in v5.1.1

Thanks
